CREATE TABLE IF NOT EXISTS appointments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(200) NOT NULL,
  start_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description TEXT NOT NULL,
  private BOOLEAN NOT NULL
);
